name: jobmentor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  http: ^1.3.0
  pdf: ^3.10.7
  path_provider: ^2.1.2
  open_filex: ^4.3.2
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2
  file_picker: ^10.0.0
  path: ^1.9.1
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  file_selector_windows: ^0.9.3+4
  url_launcher: ^6.1.7
  url_launcher_windows: ^3.1.4
  geolocator: ^14.0.0         # add for location detection
  geocoding: ^3.0.0           # add for reverse-geocoding
  html_unescape: ^2.0.0       # for removing unwanted charater
  flutter_speed_dial: ^7.0.0  # for animated add and refresh button
  google_sign_in: ^6.1.4      # google signin
  device_info_plus: ^11.4.0
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_launcher_icons: ^0.14.3    #for logo of the app
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/jobmentor_logo.png"  # your logo here

flutter:
  uses-material-design: true

  assets:
    - assets/profile_placeholder.png
    - assets/register_background.jpg
    - assets/login_background.jpg
    - assets/google_logo.png
    
